packages:
  - apps/*
  - packages/*

catalog:
  '@types/node': ^24.6.2
  '@types/react': 19.2.0
  '@types/react-dom': 19.2.0
  eslint: ^9.36.0
  react: ^19.2.0
  react-dom: 19.2.0
  typescript: ^5.9.3
  vite: ^7.1.7

onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
  - unrs-resolver

overrides:
  '@eslint/config-helpers': ^0.3.1
